server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true