server:
  port: 9091

spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka