server:
  port: 9090

spring:
  application:
   name: UserService
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:9094

#spring.config.import.optional.configserver=http://localhost:9094

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka