server:
  port: 9090

spring:
  application:
   name: UserService
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:9094
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-78809237.okta.com/oauth2/default
      client:
        provider:
          okta:
            issuerUri: https://dev-78809237.okta.com/oauth2/default
        registration:
          my-internal-client:
            provider: okta
            authorizationGrantType: client_credentials
            scope:
              - internal
            clientId: 0oamxukoeo7SnfBWL5d7
            client-secret: Iw544Hhi4s1a9b1r5wOErIr_f5ZW70cLJNsKHUo0H-sgoBDJmhgpqCGyXgEYY4An

#spring.config.import.optional.configserver=http://localhost:9094

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s


okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default




