server:
  port: 9092


spring:
  application:
    name: RatingService
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices
      auto-index-creation: true
    jpa:
      repositories:
        enabled: true
  main:
    allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-78809237.okta.com/oauth2/default
          audiences:
            - api://default


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


okta:
  oauth2:
    issuer: https://dev-77584981.okta.com/oauth2/default
    audience: api://default


#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://raghukiran4590:6li4e3mv4Ch4zv3r@cluster0.gehwm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: microservices
#      auto-index-creation: true
#    jpa:
#      repositories:
#        enabled:
#  main:
#    allow-circular-references: true

#logging:
#  level:
#    root: "debug"